/**
 * Style Dictionary v4 configuration
 * Idox Design System — Token Build Pipeline
 *
 * Outputs:
 *   - dist/tokens.css          CSS custom properties (semantic layer only)
 *   - dist/tokens-full.css     CSS custom properties (primitive + semantic)
 *   - dist/tailwind-tokens.mjs Tailwind theme extension (ESM)
 *   - dist/tokens-flat.json    Flat resolved JSON (for UNIFACE / other platforms)
 *
 * Token file structure:
 *   primitive.json  — raw values, wrapped under a top-level "primitive" key
 *   semantic.json   — purpose-driven aliases, flat at root level
 *
 * Because primitive.json has a "primitive" wrapper, token paths are:
 *   primitive tokens → ['primitive', 'blue', '800']
 *   semantic tokens  → ['interactive', 'default']
 *
 * Semantic tokens reference primitives as {primitive.blue.800} which
 * resolves correctly against the primitive.json structure.
 */

import StyleDictionary from 'style-dictionary';

// ---------------------------------------------------------------------------
// Semantic token top-level keys — used for filtering output to semantic only
// ---------------------------------------------------------------------------
const SEMANTIC_KEYS = [
  'spacing', 'brand', 'interactive', 'surface', 'border', 'text',
  'success', 'danger', 'warning', 'info', 'opacity',
  'typography', 'effects', 'borderRadius', 'borderWidth',
];

const isSemantic = (token) => SEMANTIC_KEYS.includes(token.path[0]);

// ---------------------------------------------------------------------------
// Custom transforms
// ---------------------------------------------------------------------------

/**
 * Fix: half-step spacing keys like "0.5", "1.5" are nested inside their
 * parent key — e.g. spacing.0.5 lives under spacing.0, producing a path
 * of ['primitive', 'spacing', '0', '5']. We merge the last two numeric
 * segments with '_' to produce safe CSS variable names: spacing-0_5 etc.
 */
StyleDictionary.registerTransform({
  name: 'name/halfstep-fix',
  type: 'name',
  filter: (token) => {
    const path = token.path;
    const last = path[path.length - 1];
    const secondLast = path[path.length - 2];
    return /^\d+$/.test(last) && /^\d+$/.test(secondLast);
  },
  transform: (token) => {
    const path = [...token.path];
    const last = path.pop();
    const secondLast = path.pop();
    return [...path, `${secondLast}_${last}`].join('-');
  },
});

// ---------------------------------------------------------------------------
// Custom formats
// ---------------------------------------------------------------------------

/**
 * CSS variables format — wraps output in :root {}, skips composite
 * typography objects (no CSS shorthand exists), adds inline comments.
 */
StyleDictionary.registerFormat({
  name: 'css/idox-variables',
  format: ({ dictionary, options }) => {
    const header = `/**
 * Idox Design System — CSS Custom Properties
 * Auto-generated by Style Dictionary. Do not edit manually.
 * Sources: primitive.json, semantic.json
 */\n\n`;

    const vars = dictionary.allTokens
      .filter((token) => token.value !== null && token.value !== undefined)
      .filter((token) => typeof token.value !== 'object')
      .map((token) => {
        const comment = token.comment || token.$description || token.description;
        const commentStr = comment ? ` /* ${comment} */` : '';
        return `  --${token.name}: ${token.value};${commentStr}`;
      })
      .join('\n');

    const selector = options?.selector ?? ':root';
    return `${header}${selector} {\n${vars}\n}\n`;
  },
});

/**
 * Tailwind theme extension — ESM object ready to spread into
 * tailwind.config.js theme.extend. Values reference CSS custom properties
 * so tokens.css must be imported in the global stylesheet.
 */
StyleDictionary.registerFormat({
  name: 'tailwind/idox-theme',
  format: ({ dictionary }) => {
    const colors = {};
    const spacing = {};
    const borderRadius = {};
    const borderWidth = {};
    const boxShadow = {};
    const fontSize = {};
    const fontWeight = {};
    const fontFamily = {};
    const letterSpacing = {};

    dictionary.allTokens
      .filter((t) => t.value !== null && typeof t.value !== 'object')
      .forEach((token) => {
        const val = `var(--${token.name})`;
        const type = token.$type || token.type;
        const path = token.path;

        if (type === 'color') {
          const [group, ...rest] = path;
          if (!colors[group]) colors[group] = {};
          colors[group][rest.join('-') || 'DEFAULT'] = val;
        } else if (type === 'spacing') {
          spacing[path.join('-')] = val;
        } else if (type === 'borderRadius') {
          borderRadius[path.join('-')] = val;
        } else if (type === 'borderWidth') {
          borderWidth[path.join('-')] = val;
        } else if (type === 'boxShadow') {
          boxShadow[path.join('-')] = val;
        } else if (type === 'fontSize') {
          fontSize[path.join('-')] = val;
        } else if (type === 'fontWeight') {
          fontWeight[path.join('-')] = val;
        } else if (type === 'fontFamily') {
          fontFamily[path.join('-')] = val;
        } else if (type === 'letterSpacing') {
          letterSpacing[path.join('-')] = val;
        }
      });

    const theme = {
      colors, spacing, borderRadius, borderWidth,
      boxShadow, fontSize, fontWeight, fontFamily, letterSpacing,
    };

    return `/**
 * Idox Design System — Tailwind Theme Extension
 * Auto-generated by Style Dictionary. Do not edit manually.
 *
 * Usage in tailwind.config.js:
 *   import idoxTokens from './tailwind-tokens.mjs';
 *   export default { theme: { extend: idoxTokens } };
 *
 * Note: Values reference CSS custom properties.
 * Ensure dist/tokens.css is imported in your global stylesheet.
 */

export default ${JSON.stringify(theme, null, 2)};
`;
  },
});

/**
 * Flat JSON — resolved key:value map for non-web platforms (e.g. UNIFACE).
 * All references are fully resolved to their final values.
 */
StyleDictionary.registerFormat({
  name: 'json/idox-flat',
  format: ({ dictionary }) => {
    const flat = {};
    dictionary.allTokens
      .filter((t) => t.value !== null && typeof t.value !== 'object')
      .forEach((token) => {
        flat[token.name] = {
          value: token.value,
          type: token.$type || token.type,
          description: token.comment || token.$description || token.description || '',
        };
      });
    return JSON.stringify(flat, null, 2) + '\n';
  },
});

// ---------------------------------------------------------------------------
// Style Dictionary instance
// ---------------------------------------------------------------------------

const sd = new StyleDictionary({
  source: ['primitive.json', 'semantic.json'],

  log: {
    warnings: 'warn',
    verbosity: 'verbose',
  },

  platforms: {

    // ------------------------------------------------------------------
    // 1. CSS — semantic tokens only (for production use)
    // ------------------------------------------------------------------
    css: {
      transformGroup: 'css',
      transforms: ['name/halfstep-fix'],
      files: [
        {
          destination: 'dist/tokens.css',
          format: 'css/idox-variables',
          options: {
            selector: ':root',
            outputReferences: false,
          },
          filter: isSemantic,
        },
      ],
    },

    // ------------------------------------------------------------------
    // 2. CSS — full output including primitives (for debugging)
    // ------------------------------------------------------------------
    'css-full': {
      transformGroup: 'css',
      transforms: ['name/halfstep-fix'],
      files: [
        {
          destination: 'dist/tokens-full.css',
          format: 'css/idox-variables',
          options: {
            selector: ':root',
            outputReferences: false,
          },
        },
      ],
    },

    // ------------------------------------------------------------------
    // 3. Tailwind theme extension (semantic only)
    // ------------------------------------------------------------------
    tailwind: {
      transformGroup: 'js',
      transforms: ['name/halfstep-fix'],
      files: [
        {
          destination: 'dist/tailwind-tokens.mjs',
          format: 'tailwind/idox-theme',
          filter: isSemantic,
        },
      ],
    },

    // ------------------------------------------------------------------
    // 4. Flat JSON — resolved values for non-web platforms (semantic only)
    // ------------------------------------------------------------------
    json: {
      transformGroup: 'js',
      transforms: ['name/halfstep-fix'],
      files: [
        {
          destination: 'dist/tokens-flat.json',
          format: 'json/idox-flat',
          filter: isSemantic,
        },
      ],
    },
  },
});

export default sd;
