/**
 * Style Dictionary v4 configuration
 * Idox Design System — Token Build Pipeline
 *
 * Outputs:
 *   - tokens.css          CSS custom properties (semantic layer only)
 *   - tokens-full.css     CSS custom properties (primitive + semantic)
 *   - tailwind-tokens.mjs Tailwind theme extension (ESM)
 *   - tokens-flat.json    Flat resolved JSON (for UNIFACE / other platforms)
 */

import StyleDictionary from 'style-dictionary';

// ---------------------------------------------------------------------------
// Custom transforms
// ---------------------------------------------------------------------------

/**
 * Fix: half-step spacing keys like "0.5", "1.5" are nested inside their
 * parent key in the token file (spacing.0.5 lives under spacing.0).
 * Style Dictionary path arrays represent this as ['spacing', '0', '5'] which
 * would produce --spacing-0-5. We intercept and re-join with a dot so the
 * output becomes --spacing-0\.5 … actually we convert to a safe name:
 * spacing-0_5, spacing-1_5 etc.
 */
StyleDictionary.registerTransform({
  name: 'name/halfstep-fix',
  type: 'name',
  filter: (token) => {
    const path = token.path.join('.');
    return /\.\d+\.\d+$/.test(path); // ends in two numeric segments
  },
  transform: (token) => {
    // Join path with hyphens but merge the last two numeric segments with '_'
    const path = [...token.path];
    const last = path.pop();
    const secondLast = path.pop();
    // e.g. ['primitive', 'spacing', '0', '5'] → 'primitive-spacing-0_5'
    return [...path, `${secondLast}_${last}`].join('-');
  },
});

/**
 * Fix: resolve composite typography $value objects (which contain nested
 * references) to a CSS comment placeholder — CSS has no single typography
 * shorthand. These tokens are useful as documentation but can't be emitted
 * as a single variable.
 */
StyleDictionary.registerTransform({
  name: 'value/composite-typography-skip',
  type: 'value',
  filter: (token) => token.$type === 'typography' || token.type === 'typography',
  transform: () => null, // will be filtered out below
});

// ---------------------------------------------------------------------------
// Custom formats
// ---------------------------------------------------------------------------

/**
 * CSS variables format — wraps output in :root {}, skips null values
 * (composite typography tokens), and adds a header comment.
 */
StyleDictionary.registerFormat({
  name: 'css/idox-variables',
  format: ({ dictionary, options }) => {
    const header = `/**
 * Idox Design System — CSS Custom Properties
 * Auto-generated by Style Dictionary. Do not edit manually.
 * Source: idox-design-system-tokens.json
 */\n\n`;

    const vars = dictionary.allTokens
      .filter((token) => token.value !== null && token.value !== undefined)
      .filter((token) => typeof token.value !== 'object') // skip unresolved composites
      .map((token) => {
        const comment = token.comment || token.$description || token.description;
        const commentStr = comment ? ` /* ${comment} */` : '';
        return `  --${token.name}: ${token.value};${commentStr}`;
      })
      .join('\n');

    const selector = options?.selector ?? ':root';
    return `${header}${selector} {\n${vars}\n}\n`;
  },
});

/**
 * Tailwind theme extension format — outputs an ESM object ready to spread
 * into tailwind.config.js theme.extend.
 */
StyleDictionary.registerFormat({
  name: 'tailwind/idox-theme',
  format: ({ dictionary }) => {
    const colors = {};
    const spacing = {};
    const borderRadius = {};
    const borderWidth = {};
    const boxShadow = {};
    const fontSize = {};
    const fontWeight = {};
    const fontFamily = {};
    const letterSpacing = {};

    dictionary.allTokens
      .filter((t) => t.value !== null && typeof t.value !== 'object')
      .forEach((token) => {
        const val = `var(--${token.name})`;
        const type = token.$type || token.type;
        const path = token.path.filter((p) => !['semantic', 'primitive'].includes(p));

        if (type === 'color') {
          // Build nested color object: interactive.default, text.primary etc.
          const [group, ...rest] = path;
          if (!colors[group]) colors[group] = {};
          const key = rest.join('-') || 'DEFAULT';
          colors[group][key] = val;
        } else if (type === 'spacing') {
          const key = path.join('-');
          spacing[key] = val;
        } else if (type === 'borderRadius') {
          const key = path.join('-');
          borderRadius[key] = val;
        } else if (type === 'borderWidth') {
          const key = path.join('-');
          borderWidth[key] = val;
        } else if (type === 'boxShadow') {
          const key = path.join('-');
          boxShadow[key] = val;
        } else if (type === 'fontSize') {
          const key = path.join('-');
          fontSize[key] = val;
        } else if (type === 'fontWeight') {
          const key = path.join('-');
          fontWeight[key] = val;
        } else if (type === 'fontFamily') {
          const key = path.join('-');
          fontFamily[key] = val;
        } else if (type === 'letterSpacing') {
          const key = path.join('-');
          letterSpacing[key] = val;
        }
      });

    const theme = { colors, spacing, borderRadius, borderWidth, boxShadow, fontSize, fontWeight, fontFamily, letterSpacing };

    return `/**
 * Idox Design System — Tailwind Theme Extension
 * Auto-generated by Style Dictionary. Do not edit manually.
 *
 * Usage in tailwind.config.js:
 *   import idoxTokens from './tailwind-tokens.mjs';
 *   export default { theme: { extend: idoxTokens } };
 *
 * Note: This file uses CSS custom properties as values.
 * Ensure tokens.css is imported in your global stylesheet.
 */

export default ${JSON.stringify(theme, null, 2)};
`;
  },
});

/**
 * Flat JSON format — outputs a simple key:value map with resolved values.
 * Intended for UNIFACE integration or any platform that needs raw values
 * without CSS variable references.
 */
StyleDictionary.registerFormat({
  name: 'json/idox-flat',
  format: ({ dictionary }) => {
    const flat = {};
    dictionary.allTokens
      .filter((t) => t.value !== null && typeof t.value !== 'object')
      .forEach((token) => {
        flat[token.name] = {
          value: token.value,
          type: token.$type || token.type,
          description: token.comment || token.$description || token.description || '',
        };
      });

    return JSON.stringify(flat, null, 2) + '\n';
  },
});

// ---------------------------------------------------------------------------
// Style Dictionary instance
// ---------------------------------------------------------------------------

const sd = new StyleDictionary({
  // Point at both layers; primitive must come first so references resolve
  source: [
    'primitive.json', 'semantic.json'
  ],

  // Unwrap the top-level 'primitive' and 'semantic' namespaces so that
  // references like {blue.800} resolve correctly against primitive tokens
  // and semantic tokens output without 'semantic-' prefixes.
  preprocessors: ['tokens-studio'], // enable if using Tokens Studio preprocessor

  log: {
    warnings: 'warn',
    verbosity: 'default',
  },

  platforms: {

    // ------------------------------------------------------------------
    // 1. CSS — semantic tokens only (recommended for production use)
    // ------------------------------------------------------------------
    css: {
      transformGroup: 'css',
      transforms: ['name/halfstep-fix'],
      prefix: '',
      files: [
        {
          destination: 'dist/tokens.css',
          format: 'css/idox-variables',
          options: {
            selector: ':root',
            outputReferences: false, // fully resolve all values
          },
          // Only emit semantic layer tokens
          filter: (token) =>
            token.path[0] === 'semantic' ||
            !['primitive'].includes(token.path[0]),
        },
      ],
    },

    // ------------------------------------------------------------------
    // 2. CSS — full output including primitives (useful for debugging)
    // ------------------------------------------------------------------
    'css-full': {
      transformGroup: 'css',
      transforms: ['name/halfstep-fix'],
      files: [
        {
          destination: 'dist/tokens-full.css',
          format: 'css/idox-variables',
          options: {
            selector: ':root',
            outputReferences: false,
          },
        },
      ],
    },

    // ------------------------------------------------------------------
    // 3. Tailwind theme extension
    // ------------------------------------------------------------------
    tailwind: {
      transformGroup: 'js',
      transforms: ['name/halfstep-fix'],
      files: [
        {
          destination: 'dist/tailwind-tokens.mjs',
          format: 'tailwind/idox-theme',
          filter: (token) => token.path[0] === 'semantic',
        },
      ],
    },

    // ------------------------------------------------------------------
    // 4. Flat JSON — resolved values for non-web platforms (e.g. UNIFACE)
    // ------------------------------------------------------------------
    json: {
      transformGroup: 'js',
      transforms: ['name/halfstep-fix'],
      files: [
        {
          destination: 'dist/tokens-flat.json',
          format: 'json/idox-flat',
          filter: (token) => token.path[0] === 'semantic',
        },
      ],
    },
  },
});

export default sd;
