/**
 * Style Dictionary v4 configuration
 * Idox Design System — Token Build Pipeline
 *
 * Token file structure:
 *   primitive.json  — raw values, wrapped under a top-level "primitive" key
 *                     token paths: ['primitive', 'blue', '800']
 *   semantic.json   — purpose-driven aliases, flat at root level
 *                     token paths: ['interactive', 'default']
 */

import StyleDictionary from 'style-dictionary';

// ---------------------------------------------------------------------------
// Semantic token top-level keys — used to filter output to semantic layer only
// ---------------------------------------------------------------------------
const SEMANTIC_KEYS = [
  'spacing', 'brand', 'interactive', 'surface', 'border', 'text',
  'success', 'danger', 'warning', 'info', 'opacity',
  'typography', 'effects', 'borderRadius', 'borderWidth',
];

const isSemantic = (token) => SEMANTIC_KEYS.includes(token.path[0]);
const isNotComposite = (token) => typeof token.value !== 'object';

// ---------------------------------------------------------------------------
// Custom formats
// ---------------------------------------------------------------------------

StyleDictionary.registerFormat({
  name: 'css/idox-variables',
  format: ({ dictionary, options }) => {
    const header = `/**
 * Idox Design System — CSS Custom Properties
 * Auto-generated by Style Dictionary. Do not edit manually.
 * Sources: primitive.json, semantic.json
 */\n\n`;

    const vars = dictionary.allTokens
      .filter(isNotComposite)
      .filter((token) => token.value !== null && token.value !== undefined)
      .map((token) => {
        const comment = token.$description || token.description || token.comment;
        const commentStr = comment ? ` /* ${comment} */` : '';
        // Build CSS variable name from path, joining with hyphens
        const name = token.path.join('-');
        return `  --${name}: ${token.value};${commentStr}`;
      })
      .join('\n');

    const selector = options?.selector ?? ':root';
    return `${header}${selector} {\n${vars}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'tailwind/idox-theme',
  format: ({ dictionary }) => {
    const colors = {};
    const spacing = {};
    const borderRadius = {};
    const borderWidth = {};
    const boxShadow = {};
    const fontSize = {};
    const fontWeight = {};
    const fontFamily = {};
    const letterSpacing = {};

    dictionary.allTokens
      .filter(isNotComposite)
      .filter((token) => token.value !== null)
      .forEach((token) => {
        const cssVar = `var(--${token.path.join('-')})`;
        const type = token.$type || token.type;
        const [group, ...rest] = token.path;

        if (type === 'color') {
          if (!colors[group]) colors[group] = {};
          colors[group][rest.join('-') || 'DEFAULT'] = cssVar;
        } else if (type === 'spacing') {
          spacing[token.path.join('-')] = cssVar;
        } else if (type === 'borderRadius') {
          borderRadius[rest.join('-') || group] = cssVar;
        } else if (type === 'borderWidth') {
          borderWidth[rest.join('-') || group] = cssVar;
        } else if (type === 'boxShadow') {
          boxShadow[token.path.join('-')] = cssVar;
        } else if (type === 'fontSize') {
          fontSize[rest.join('-') || group] = cssVar;
        } else if (type === 'fontWeight') {
          fontWeight[rest.join('-') || group] = cssVar;
        } else if (type === 'fontFamily') {
          fontFamily[rest.join('-') || group] = cssVar;
        } else if (type === 'letterSpacing') {
          letterSpacing[rest.join('-') || group] = cssVar;
        }
      });

    const theme = {
      colors, spacing, borderRadius, borderWidth,
      boxShadow, fontSize, fontWeight, fontFamily, letterSpacing,
    };

    return `/**
 * Idox Design System — Tailwind Theme Extension
 * Auto-generated by Style Dictionary. Do not edit manually.
 *
 * Usage in tailwind.config.js:
 *   import idoxTokens from './tailwind-tokens.mjs';
 *   export default { theme: { extend: idoxTokens } };
 *
 * Ensure dist/tokens.css is imported in your global stylesheet.
 */

export default ${JSON.stringify(theme, null, 2)};
`;
  },
});

StyleDictionary.registerFormat({
  name: 'json/idox-flat',
  format: ({ dictionary }) => {
    const flat = {};
    dictionary.allTokens
      .filter(isNotComposite)
      .filter((token) => token.value !== null)
      .forEach((token) => {
        flat[token.path.join('-')] = {
          value: token.value,
          type: token.$type || token.type,
          description: token.$description || token.description || token.comment || '',
        };
      });
    return JSON.stringify(flat, null, 2) + '\n';
  },
});

// ---------------------------------------------------------------------------
// Style Dictionary instance
// ---------------------------------------------------------------------------

const sd = new StyleDictionary({
  source: ['primitive.json', 'semantic.json'],

  log: {
    warnings: 'warn',
    verbosity: 'verbose',
  },

  platforms: {

    // 1. CSS — semantic tokens only (production)
    css: {
      transforms: ['attribute/cti', 'color/hex', 'size/rem'],
      files: [
        {
          destination: 'dist/tokens.css',
          format: 'css/idox-variables',
          options: { selector: ':root', outputReferences: false },
          filter: isSemantic,
        },
      ],
    },

    // 2. CSS — full output including primitives (debugging)
    'css-full': {
      transforms: ['attribute/cti', 'color/hex', 'size/rem'],
      files: [
        {
          destination: 'dist/tokens-full.css',
          format: 'css/idox-variables',
          options: { selector: ':root', outputReferences: false },
        },
      ],
    },

    // 3. Tailwind theme extension
    tailwind: {
      transforms: ['attribute/cti', 'color/hex', 'size/rem'],
      files: [
        {
          destination: 'dist/tailwind-tokens.mjs',
          format: 'tailwind/idox-theme',
          filter: isSemantic,
        },
      ],
    },

    // 4. Flat JSON for non-web platforms (e.g. UNIFACE)
    json: {
      transforms: ['attribute/cti', 'color/hex'],
      files: [
        {
          destination: 'dist/tokens-flat.json',
          format: 'json/idox-flat',
          filter: isSemantic,
        },
      ],
    },
  },
});

export default sd;
